sonar.verbose=true
sonar.organization=saitech01-mykey
sonar.projectKey=saitech01-mykey_saitech01-project1
sonar.projectName=Saitech01_Project1
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
